### ISSUE TITLE
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Double

### ISSUE THREAD

**Issue by Xicad** [ReportCardsMC/SKNoise#12]
**Describe the bug**
Strange console error that says java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Double

When I use a script i was making, when it tries to generate a cavern nothing happens and this error shows up in console.
**To Reproduce**

1 - add this to scripts folder https://gist.github.com/Xicad/b3b01a2f808060949026b51c0afeab0c
2 - run the command /cave, it should broadcast where a cavern is but nothing happens and this error shows up in the console: https://gist.github.com/Xicad/130fdeecf5c1e3606a32117b644c32a8
**Expected behavior**

I expected the error to not happen
**Screenshots**

**Additional context**

**Comment by ReportCardsMC** [comment]
I'm like 75% sure I recently fixed this but a new release with it has not been released yet! I will still check this issue out very shortly, sorry for the issue. It's likely due to setting octaves higher than 8 and/or the fact you're just using octaves at all sometimes does that. (Octaves max out at 8, there's no reason to go higher, it'll just cause more lag to the server)

**Comment by Xicad** [comment]
Still happens with octaves set to 3 (im on 0.1.7)

**Comment by ReportCardsMC** [comment]
Alrighty, I'll see if it's not already fixed in 0.1.8

**Comment by ReportCardsMC** [comment]
This issue seems to be fixed in the new version, expect to see a release in 1-3 days @Xicad
